Wrong notification action button removed.
NJACKWinterOfCode/android-productivity-timer-tametu-app pull request #11
Opened 2018-12-05 22:48 UTC by somenath1435

fixes #10 
I've removed the complete action button on notifications.

2018-12-05 22:50 UTC, codersanjeev approved these changes

2018-12-06 11:50 UTC, numerative requested changes

2018-12-06 11:50 UTC, numerative commented on app/src/main/java/gis2018/udacity/pomodoro/CountDownTimerService.java
> -                .addAction(R.drawable.complete, "Complete", completeActionPendingIntent)
Hey @somenath1435 ,
Removing this line would remove the Complete action button altogether, even when the Session timer is running.

What is required is for it to be removed only when the break is running.

2018-12-07 11:11 UTC, numerative commented
Hey @somenath1435,
This issue has been resolved.

2018-12-07 11:11 UTC, closed without merging