Fixed issue of task name
NJACKWinterOfCode/android-productivity-timer-tametu-app pull request #33
Opened 2018-12-15 20:46 UTC by chanmol1999

##now the task name is recalled in the app every time even after you clear the app from device memory.

Fixes #19 

## Type of change
Just put an x in the [] which are valid.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings

2018-12-15 21:31 UTC, thedevelopersanjeev commented
By default, the task name is empty in the starting. Give it some default name such as "Task 1" initially instead of showing an empty edittext. @chanmol1999

2018-12-15 21:51 UTC, chanmol1999 commented
At the launch of app first time  Task 1 is displayed as far my concern.Please check.

2018-12-15 21:54 UTC, thedevelopersanjeev commented
Uninstall the old apk and reinstall...

![screenshot_20181216-032149](https://user-images.githubusercontent.com/34043056/50047763-eddf8080-00e1-11e9-9ec1-47d05bd62e3b.png)

2018-12-15 21:55 UTC, chanmol1999 commented
Please review it.

2018-12-15 22:09 UTC, codersanjeev requested changes

2018-12-15 22:09 UTC, thedevelopersanjeev commented on app/src/main/res/layout/activity_main.xml
> +                android:hint="@string/task_name"
The hint should be something like "Enter the task name here".

2018-12-16 07:45 UTC, chanmol1999 commented
Please check it now

2018-12-16 10:43 UTC, codersanjeev approved these changes

2018-12-16 11:28 UTC, merged